version: "3"

services: 
    backshilap:
      container_name: backend-shilap
      restart: always
      build: .
      ports: 
          - "3000:3000"
      links: 
          - mongo
    mongo:
      container_name: dbmongo
      image: mongo
      ports: 
          - "27017:27017"
      logging: 
          driver: none